from langgraph.graph import StateGraph, START, END
from app.agents.state import PipelineState
from app.agents.retriever import retriever_node, create_event
from app.agents.analyst import analyst_node
from app.agents.critic import critic_node
from app.agents.formatter import formatter_node
from app.agents.router import router_node
from app.core.event_bus import EventBus
import time

def should_revise(state: PipelineState) -> str:
    if state.get("needs_revision", False):
        return "analyst"
    return "formatter"

def route_query(state: PipelineState) -> str:
    intent = state.get("intent", "search")
    if intent == "chat":
        return END
    return "retriever"

workflow = StateGraph(PipelineState)

workflow.add_node("router", router_node)
workflow.add_node("retriever", retriever_node)
workflow.add_node("analyst", analyst_node)
workflow.add_node("critic", critic_node)
workflow.add_node("formatter", formatter_node)

workflow.add_edge(START, "router")
workflow.add_conditional_edges("router", route_query)
workflow.add_edge("retriever", "analyst")
workflow.add_edge("analyst", "critic")
workflow.add_conditional_edges("critic", should_revise)
workflow.add_edge("formatter", END)

app = workflow.compile()

async def run_pipeline(query: str, event_bus: EventBus) -> PipelineState:
    initial_state = {
        "query": query,
        "revision_count": 0,
        "events": [],
        "needs_revision": False
    }
    
    final_state = None
    start_time = time.time()
    
    # REVISED PIPELINE EXECUTION TO SUPPORT REAL-TIME EMITS
    # Since nodes are synchronous functions in our setup, they can't await event_bus.emit.
    # Therefore, they return events in the state update, and we process them here.
    
    try:
        current_state = initial_state
        async for event in app.astream(initial_state):
            for node_name, state_update in event.items():
                if "events" in state_update:
                    for e in state_update["events"]:
                        await event_bus.emit(e)
                # Update current_state for the final return
                for k, v in state_update.items():
                    if k == "events":
                        if "events" not in current_state:
                            current_state["events"] = []
                        current_state["events"].extend(v)
                    else:
                        current_state[k] = v
        
        # Emit final complete event
        duration = time.time() - start_time
        
        if current_state.get("error"):
            await event_bus.emit(create_event("pipeline", "error", "Pipeline failed", 100, {"error": current_state.get("error")}))
        elif current_state.get("final_response") is None:
            await event_bus.emit(create_event("pipeline", "error", "Pipeline failed", 100, {"error": "No response generated by pipeline."}))
        else:
            await event_bus.emit(create_event("pipeline", "complete", "Done", 100, {
                "duration": duration,
                "final_response": current_state.get("final_response"),
                "citations": current_state.get("citations"),
                "confidence_score": current_state.get("confidence_score")
            }))
        return current_state
    except Exception as e:
        await event_bus.emit(create_event("pipeline", "error", "Pipeline failed", 100, {"error": str(e)}))
        return current_state
